### ISSUE TITLE
Core docs return a 404

### ISSUE THREAD

**Issue by noffle** [dominictarr/readme#17]
Someone changed all of the node core docs to be .markdown instead of .md. I've submitted a PR (https://github.com/eush77/node-api-docs/pull/1) to fix this on `node-api-docs`, so we just need to update here once that's in.

**Comment by eush77** [comment]
`node-api-docs@0.3.1` is published and I believe we don't need to update here since it's covered in the current version range.

Thank you!

**Comment by noffle** [comment]
Oh perfect! Thanks for noticing this @eush77.
